###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "uid":"ABCD123",
    "name":"gordo 2",
    "lastName":"Benavides",
    "email":"gordo@hotmail.com"
}

###
get http://localhost:9000/api/users HTTP/1.1

###
get http://localhost:9000/api/users/ABCD123 HTTP/1.1

###
PUT http://localhost:9000/api/users/636d19dd656357afd88917b8 HTTP/1.1
Content-Type: application/json

{
    "name":"kevin Vargas",
    "age": 28,
    "email":"gordo@hotmail.com"
}
###
DELETE http://localhost:9000/api/users/636d19dd656357afd88917b8 HTTP/1.1